### ISSUE TITLE
Compilation errors are not shown in console when sourceMap is set to true

### ISSUE THREAD

**Issue by wujekbogdan** [sindresorhus/grunt-sass#117]
When I set **sourceMap** to **true** and run **grunt build** then in case of compilation error nothing is shown in the console except:

> Running "sass:dist" (sass) task

and that's it. No errors at all.

> "node-sass": "~0.7.0",
> "grunt-sass": "^0.14.0"
> "grunt": "~0.4.1",

**Comment by HugoGiraudel** [comment]
Has this ever been fixed?

**Comment by kevva** [comment]
@HugoGiraudel, yes since `1.0.0`, when we bumped `node-sass`.
