### ISSUE TITLE
SCSS files in different directory

### ISSUE THREAD

**Issue by joelworsham** [sindresorhus/grunt-sass#145]
My project file structure looks something like this (for applicable files):

-assets
--css
--scss

So my css files are in a completely different directory. When I set sourceMap to "true", the source map "sources" are not pointing to the correct directory. They're pointing relative to the css directory, so they're looking for the source scss files like this:

-assets
--css
---assets
----scss

**Comment by sindresorhus** [comment]
https://github.com/sass/node-sass/issues/new
