### ISSUE TITLE
Option for inlined source maps

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/grunt-sass#155]
Source maps have the `sourcesContent` property, allowing for embedding contents directly in source maps. This eliminates the problem with resolving the path to the original Sass file.

This was already implemented in libsass in sass/libsass#591 and is in planning to come to node-sass soon in https://github.com/sass/node-sass/issues/372#issuecomment-61538389

Once it's in node-sass, can this be included in grunt-sass too?

**Comment by shanesmith** [comment]
Unless I'm missing something, embedded sourcemaps is implemented in node-sass v2.0.0-beta, so I think this issue is still open until it gets out of beta and we bump up to that...?
