### ISSUE TITLE
Source Map

### ISSUE THREAD

**Issue by dawidk92** [sindresorhus/grunt-sass#166]
Version: 17.0
1) Source map shows me in DevTools both scss and css files
2) It shows me wrong files and wrong lines of scss files

![zrzut ekranu 2014-12-09 o 10 00 22](https://cloud.githubusercontent.com/assets/7023167/5354607/87401132-7f8a-11e4-9cde-f5ba890a2912.png)
![zrzut ekranu 2014-12-09 o 10 03 43](https://cloud.githubusercontent.com/assets/7023167/5354616/bbcc4d1c-7f8a-11e4-8268-c01bfcbb3c0b.png)

**Comment by joelworsham** [comment]
+1 for fix. Same issue (Libsass + Autoprefixer + Sourcemaps + Foundation)(though problem persists without Autoprefixer as well)

**Comment by sindresorhus** [comment]
libsass has had a lot of problems with source maps. Most should have been fixed in the latest libsass.

See: https://github.com/sindresorhus/grunt-sass/issues/170
