### ISSUE TITLE
node-sass 2.0 support

### ISSUE THREAD

**Issue by wintercounter** [sindresorhus/grunt-sass#170]
node-sass 2.0 (beta) is out now. I was wondering when we can get grunt-sass 2.0 (beta) also as it has the latest Libsass binary which brings better Sass 3.3 support.

**Comment by sindresorhus** [comment]
When 2.0 final ships.

**Comment by Dynasty9** [comment]
I can't build on my centos machine which causes me a significant issue.

**Comment by pierremanceaux** [comment]
+1 :)

**Comment by wintercounter** [comment]
To be honest, i couldn't wait so i've made my own build. It's not hard, you
only need to care about file saving as of 2.0, node-sass will only give the
output in a variable. Save with FS and call grunt's next() in the callback.

**Comment by framerate** [comment]
Apparently node-sass current won't build with node 0.11, but if anyone has a work around let me know. 

```
> node-sass@1.2.3 postinstall /home/travis/build/HaveKarma/web/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js
`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
```

**Comment by subsend** [comment]
please Update to node-sass to 2.0.0
Failed at the node-sass@1.2.3 postinstall script.
[INFO] npm ERR! This is most likely a problem with the node-sass package,
[INFO] npm ERR! not with npm itself.
[INFO] npm ERR! Tell the author that this fails on your system:
[INFO] npm ERR!     node scripts/build.js
[INFO] npm ERR! You can get their info via:
[INFO] npm ERR!     npm owner ls node-sass
[INFO] npm ERR! There is likely additional logging output above.

thanks

**Comment by hershmire** [comment]
@wintercounter You have that up somewhere?

> To be honest, i couldn't wait so i've made my own build. It's not hard, you
only need to care about file saving as of 2.0, node-sass will only give the
output in a variable. Save with FS and call grunt's next() in the callback.

**Comment by justafish** [comment]
@hershmire You can pull from master here https://github.com/justafish/grunt-sass

I created a PR here https://github.com/sindresorhus/grunt-sass/pull/179 which isn't intended to be merged until 2.0.0 is released, but I thought it'd be good to leave open for now

**Comment by sndrs** [comment]
@justafish that's brilliant - thanks a lot. 

v keen to try and get this working, was wonder if there is there any way to enable more verbose error reporting? doesnt' seem to be much in nodesass from what i can tell, but I'm currently getting `Warning: error reading values after *` error but with about 150 partials it's bit hard to track down…

**Comment by michaelBenin** [comment]
Also having issues with node-sass v1.2.3


````
[jenkins@ksopdtestjs04 node_modules]$ npm i node-sass@1.2.3
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
/
> node-sass@1.2.3 install /var/www/industryweek-node/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /var/www/industryweek-node/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /var/www/industryweek-node/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /var/www/industryweek-node/node_modules/node-sass/vendor/linux-x64/binding.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/industryweek-node/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "/home/jenkins/.nvm/v0.10.33/bin/node" "/home/jenkins/.nvm/v0.10.33/bin/npm" "i" "node-sass@1.2.3"
npm ERR! cwd /var/www/industryweek-node/node_modules
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
[jenkins@ksopdtestjs04 node_modules]$ 
````

**Comment by michaelBenin** [comment]
@Dynasty9 do you have a fork with an updated version for building on centos?

**Comment by sindresorhus** [comment]
Finally out: https://github.com/sindresorhus/grunt-sass/releases/tag/v0.18.0 :dancer:
