### ISSUE TITLE
when i upgrade to 0.17.0 my sass won't compile any longer.  invalid top-level expression error

### ISSUE THREAD

**Issue by xtianus79** [sindresorhus/grunt-sass#172]
below is the settings I have in total.  The only thing giving me problems is the grunt-sass version... 

when I revert back to 0.16.0 and then to 0.16.1 it works fine.  I can get both of those versions working correctly.  

specifically when I run 'grunt compile-sass' i get the following error.  

grunt compile-sass
running "sass:dist": <sass> task
warning: m:/sites/test/app/scss/components/style-guid:8: invalid top-level expression

{
  "name": "zf5_project",
  "description": "",
  "version": "0.0.1",
  "homepage": "",
  "author": {
    "name": "",
    "email": ""
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-concat": "~0.5.0",
    "grunt-contrib-connect": "~0.9.0",
    "grunt-contrib-copy": "~0.7.0",
    "grunt-contrib-cssmin": "~0.11.0",
    "grunt-contrib-imagemin": "0.9.2",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-uglify": "~0.7.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-newer": "~1.1.0",
    "grunt-sass": "~0.17.0",
    "grunt-usemin": "^3.0.0",
    "grunt-wiredep": "~2.0.0",
    "load-grunt-tasks": "~2.0.0",
    "node-sass": "~1.2.3"
  }
}

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/grunt-sass/issues/48
