### ISSUE TITLE
Error: cannot add or subtract numbers with incompatible units

### ISSUE THREAD

**Issue by xtianus79** [sindresorhus/grunt-sass#173]
this is becoming a real head scratcher.  

If i go to version .17 I get a top level expression error.  if I go back down to .16 I get the above error.  I had my configuration working well and through some changes I decided to create a new project and put my scss file in place of the old ones.  now I keep getting these errors.

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the libsass [issue tracker](https://github.com/hcatlin/libsass/issues).*

**Comment by xtianus79** [comment]
ok but there is something in relation to grunt-sass because based on the version I choose I get varying results.  so while this may be an issue with libbsass it is permeating through grunt-sass
