### ISSUE TITLE
if I am having an issue with grunt-sass and the answer is related to libsass would the latest version of libsass for grunt-sass be the issue?

### ISSUE THREAD

**Issue by xtianus79** [sindresorhus/grunt-sass#174]
if the latest version is 3.1.0 and I am having a problem with grunt-sass through libsass wouldn't a way to handle it be to update grunt-sass to the most stable release of libsass?

**Comment by sindresorhus** [comment]
Yes, but grunt-sass have to wait for the next stable version of node-sass, which is the libsass node binding. It should be out soon though.
