### ISSUE TITLE
Grunt task is done but no files created

### ISSUE THREAD

**Issue by foria** [sindresorhus/grunt-sass#175]
Hello

I'm try to compile with your library using Grunt.
Grunt finish his (unique) task without errors, but the compiled CSS is not created.

Can you help me please?

This is my Gruntfile.js

<code>module.exports = function(grunt) {

    require('load-grunt-tasks')(grunt);

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sass: {
            options: {
                sourceMap: true
            },
            dist: {
                files: {
                    'skin/frontend/default/css/style.css': 'skin/frontend/default/scss/style.scss'
                }
            }
        }
    });

    grunt.registerTask('server', [
        'sass'
    ]);
};
</code>

**Comment by sindresorhus** [comment]
Can you include the terminal output from when you installed the task? You probably had an install error.

**Comment by foria** [comment]
I uninstalled it and then reinstalled:

<code>➜  amorelie git:(yo_integration) ✗ sudo npm install --save-dev grunt-sass
npm WARN package.json amorelie@0.1.0 No repository field.
/
> node-sass@1.2.3 install /Applications/MAMP/htdocs/amorelie/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Applications/MAMP/htdocs/amorelie/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Applications/MAMP/htdocs/amorelie/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
Binary is fine; exiting
grunt-sass@0.17.0 node_modules/grunt-sass
├── object-assign@2.0.0
├── each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── node-sass@1.2.3 (get-stdin@3.0.2, object-assign@1.0.0, replace-ext@0.0.1, nan@1.5.1, shelljs@0.3.0, cross-spawn@0.2.3, mkdirp@0.5.0, meow@2.1.0, gaze@0.5.1, mocha@2.1.0, request@2.51.0)</code>

**Comment by sindresorhus** [comment]
Then I'm not sure to be honest. The tests are passing so it's most likely something with you system or more likely your SCSS. Maybe you're using some unsupported feature in libsass. The error reporting in libsass is worse to none unfortunately.

**Comment by foria** [comment]
Yeah I think so. I tried with a really simple code and it works fine.
I'm going to check what is the problem and then I'll post here for future help if needing.
Thank you very much.

**Comment by trevordmiller** [comment]
I also am not getting output files without any errors.

## main.scss

```
// PROJECT THEME

@import 'theme/vars.scss';
@import 'theme/placeholders.scss';
@import 'theme/mixins.scss';
@import 'theme/functions.scss';

// BOWER REGISTRY COMPONENTS

@import 'libs/primer-style-reset/_primer-style-reset.scss';

// PROJECT COMPONENTS

@import 'components/_components.scss';
@import 'components/home/_home.scss';
@import 'components/error/_error.scss';
@import 'components/header/_header.scss';
@import 'components/footer/_footer.scss';
@import 'components/body/_body.scss';
@import 'components/main/_main.scss';
@import 'components/button/_button.scss';
@import 'components/primer-subComponents/_primer-subComponents.scss';
```

## Example import: _header.scss

```
.header {

	// BLOCK

	@extend %padding--base;
	background: $color--primary;
	color: $color--white;

	// ELEMENTS

	&__content {
		@extend %constrain-width;
	}
}
```

**Comment by foria** [comment]
Hey Trevor, at the end I wronged the src and destination file name, this was my problem.

**Comment by macie** [comment]
@trevordmiller Are you resolved your problem with no output files?

**Comment by trevordmiller** [comment]
@macie Not sure. I ran into a few other problems (mainly lack of errors). I've moved back to Ruby Sass (`grunt-contrib-sass`) for now until Sass 3.3 features are fully supported in `node-sass` / `lib-sass` / `grunt-sass`. Can't wait ;)
