### ISSUE TITLE
Cannot compile a partial

### ISSUE THREAD

**Issue by glebm** [sindresorhus/grunt-sass#176]
I am developing a Sass library that consists only of partials. However, it seems impossible to use grunt-sass to compile non-partials. 

```js
dist: {
  files: {
    'dist/css/library.css': 'scss/_library.scss' // <- not compiled
  }
}
```
The reasons I want  only partials in the library:

1. Sass `--watch` outputs all non-prefixed files as separate CSS files. E.g. if a user copies my library  directly into the project, then imports it into their `scss/main.scss`, and runs `sass --watch`:

```console
$ sass --watch scss:public  
      write public/main.css
      write public/library.css
```

2. Compass [copies](https://github.com/Compass/compass/issues/1757#issuecomment-52563160) all non-partials in the libraries into the project when the library is added:

```console
$ compass compile
 modified config.rb
        ...
    write stylesheets/screen.css
directory stylesheets/library
    write stylesheets/library/library.css
```

---

Sister ticket: https://github.com/gruntjs/grunt-contrib-sass/issues/180

**Comment by sindresorhus** [comment]
Closing for the same reason as: https://github.com/gruntjs/grunt-contrib-sass/issues/180#issuecomment-70444421
