### ISSUE TITLE
 Tell the author that this fails on your system: 

### ISSUE THREAD

**Issue by trevordmiller** [sindresorhus/grunt-sass#178]
Tried to install via `npm install --save-dev grunt-sass` as the readme suggests, but got the following errors:

![screen shot 2015-01-21 at 11 21 30 am](https://cloud.githubusercontent.com/assets/5497885/5842102/6d9295e2-a15f-11e4-9c9c-38315241d519.png)

I would love to switch from Ruby Sass to Node Sass if this problem can be fixed. Thank you.

**Comment by sindresorhus** [comment]
Should be opened here: https://github.com/sass/node-sass

And you're using an unstable version of Node, downgrade to a stable one and it will probably work.

**Comment by trevordmiller** [comment]
@sindresorhus Sorry I posted in the wrong place. You were right, downgrading to Node stable (10.35) did the trick. Thank you!
