### ISSUE TITLE
Python build error on npm install (Windows)

### ISSUE THREAD

**Issue by JeffHerb** [sindresorhus/grunt-sass#181]
Not sure if this is an upstream issue, but when install grunt-sass via npm install on Windows 7 Enterprise I get the following issue. Grunt-sass 0.16.1 (snagged the version from another project) runs fine.

![2015-01-27_08h26_21](https://cloud.githubusercontent.com/assets/1133732/5919207/ab994f30-a5ff-11e4-8f64-fa367a835892.png)

**Comment by sindresorhus** [comment]
https://github.com/sass/node-sass/issues
