### ISSUE TITLE
sourcemaps stopped working with 0.18.1

### ISSUE THREAD

**Issue by helmus** [sindresorhus/grunt-sass#184]
I upgraded my project from `grunt-sass 0.16.1` to `0.18.1` 
Sourcemaps now stopped working almost entirely, some files still show in my inspector styles tab, but almost all files are now listed as `main.css`. 

Below config works with `0.16.1` but not with `0.18.1`

Should I add any changes ?

`Node v0.12.0` 
`Windows 7 x64` 
`chrome 40.0.2214.111 m`

        sass    : {
            options: {
                includePaths: require('node-bourbon').includePaths
            },
            dist   : {
                files: {
                    'src/css/main.css': 'src/styles/main.scss'
                }
            },
            dev    : {
                files  : {
                    'src/css/main.css': 'src/styles/main.scss'
                },
                options: {
                    sourceMap: true
                }
            }
        }

Also here is the output I get when running my `sass:dev` task with `0.18.1`

	$ node.exe C:\development\nodist\bin\node_modules\grunt-cli\bin\grunt --gruntfile C:\development\my-project\Gruntfile.js sass:dev
	Running "sass:dev" (sass) task

	Done, without errors.
	Process finished with exit code 0

As compared to `0.16.1`

	$ node.exe C:\development\nodist\bin\node_modules\grunt-cli\bin\grunt --gruntfile C:\development\my-project\Gruntfile.js sass:dev
	Running "sass:dev" (sass) task
	File src/css/main.css created.
	File src/css/main.css.map created.

	Done, without errors.
	Process finished with exit code 0

The sourcemap does get generated with the  `0.18.1` version, it just seems like it's working only partially. ( I also tried using chrome canary and node v0.10 )

**Comment by sindresorhus** [comment]
That's most likely an issue with libsass. This task is just a thin wrapper around node-sass and only writes out the sourcemap it get's back from node-sass.
