### ISSUE TITLE
issues with the compass display helper

### ISSUE THREAD

**Issue by danielrz** [sindresorhus/grunt-sass#186]
I've included "compass/reset" in my manifest file and there is an issue with compiling the following:
  @include reset-html5; (in the _utilities.scss file)
it outputs:
elements-of-type(html5-block) {
  display: block; }

instead of:
article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section, summary {
  display: block;
}

Is there something I miss?
Thank you.

**Comment by sindresorhus** [comment]
From the top of the readme:

> This task uses libsass which is a Sass compiler in C++. In contrast to the original Ruby compiler, this one is much faster, but is missing some features, though improving quickly. **It also doesn't support Compass. **
