### ISSUE TITLE
The path inside the sourcemaps isn't functioning correctly. 

### ISSUE THREAD

**Issue by acidgod** [sindresorhus/grunt-sass#190]
Hello!

I have spent two days trying to figure out how to make proper path in source map to connect them with the scss files. 

My foleder structure is as follows: 

components/sass/*.scss
components/sass/styles/*.scss

the output css file is at:

../../style.css

I managed to compile style.css file with no problem things are much faster with libsass in comparison to ruby with compass and sass, but when it comes to sourcemaps instead of creating path to scss files ( /components/sass/*.scss ) it creates the following sources paths.
		"style.scss",
		"styles/_variables.scss",

The right way would be 

		"components/sass/style.scss",
		"components/sass/styles/_variables.scss"

Is there a way to fix it ?

Here is my config for sass. 
        sass: {
            dist: {
                options: {
                    sourceMap: true,
                    includePaths: [require('node-bourbon').includePaths, 'components/sass/*.{scss,sass}', 'components/sass/**/*.{scss,sass}'],
                    outputStyle: 'nested',
                },
                // files: {
                //     '../style.css': 'sass/style.scss'
                // },
                files: [{
                    expand: true, // Enable dynamic expansion.
                    cwd: 'components/sass/', // Src matches are relative to this path.
                    src: ['*.scss'], // Actual pattern(s) to match.
                    dest: '', // Destination path prefix.
                    ext: '.css', // Dest filepaths will have this extension.
                    extDot: 'first' // Extensions in filenames begin after the first dot
                }, ],
            }
        },

**Comment by sindresorhus** [comment]
This is the issue tracker you're looking for:
https://github.com/sass/node-sass/issues/new

**Comment by mrmartineau** [comment]
@acidgod Sourcemaps are screwed up in this version because they are broken in libsass, which means node-sass is also broken. I have been following libsass's development and am hopeful that the 3.2 release will fix the sourcemap issue, then we have to wait while node-sass and grunt-sass are updated..
