### ISSUE TITLE
Task has no output

### ISSUE THREAD

**Issue by lzilioli** [sindresorhus/grunt-sass#191]
When the task succeeds, there is no output to indicate which files were written or anything of the like. This makes it difficult to debug, say, build issues on a CI server.

**Comment by sindresorhus** [comment]
```sh
grunt sass --verbose
```

**Comment by lzilioli** [comment]
@sindresorhus In my use case, this task is run as part of a much larger grunt build consisting of 10-15 other tasks that have reasonable output without invoking grunt with the verbose flag. I do not think it is reasonable, nor should it be necessary to add the noise of grunt's and all the other task's verbosity to my build logs just to get reasonable output from one task. This will increase the size of our logs, and decrease their readability, neither of which is acceptable to my team.

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt/issues/1299

**Comment by bchavezgd** [comment]
i had the same issue today. the sass tasks needed an output in sass.dist

```
sass: {
  options: {
    sourceMap: true,
    outputStyle: 'compress',
    sourceComments: true
    //outFile: 'style.css' 
      // thought i was suppose to use outfile. 
  },
  dist: {
    files: { // but i had to use 'files' instead. 
      'style.css': 'style.sass'
    }
  }
}


// in my watch task its different though. 

watch: {
  sass: {
    files: ['sass/*.*', '*.sass'],
    tasks: ['sass']
  }
}
```
from my command line, `grunt watch` and `grunt sass` work perfectly now. 

i'm not sure if this will fix your problem, but it fixed mine and i hope it helps a bit.

**Comment by lzilioli** [comment]
@bchavezgd Appreciate the input, but it sounds like your issue was around configuring your task properly. Mine is around the output that the task prints to the command line when it runs successfully. Allow me to illustrate:

```
$ grunt sass clean
Running "sass:www" (sass) task

Running "clean:www" (clean) task
>> 2 paths cleaned.

Running "clean:blog" (clean) task
>> 1 path cleaned.

Running "clean:touch" (clean) task
>> 0 paths cleaned.

Running "clean:mobile" (clean) task
>> 1 path cleaned.

Running "clean:admin" (clean) task
>> 1 path cleaned.

Running "clean:reports" (clean) task
>> 0 paths cleaned.

Done, without errors.
```

Do you notice how the clean task prints out `X path cleaned.` When it runs? This is very useful in looking over your build logs because you know that the task did what you expected it to do. On the other had, the `grunt sass` task literally has zero output. So it could have succeeded, it could have failed silently, I have no way of knowing.

Unfortunately, @sindresorhus suggestion is to run the entire grunt process with `--verbose`, which makes running the same grunt command go from the few lines you see above to 100s of lines, most of which is unnecessary. It appears his preferred course of action is to be unwilling to discuss the possibility of making this task behave in a way that is aligned with the wider grunt ecosystem, and instead reference open issues in other projects that may never get picked up or merged in.

**Comment by sindresorhus** [comment]
> So it could have succeeded, it could have failed silently, I have no way of knowing.

It will error if it fails.

> It appears his preferred course of action is to be unwilling to discuss the possibility of making this task behave in a way that is aligned with the wider grunt ecosystem

What is more sensible, get every single grunt plugin to add this boilerplate, or fix it in grunt.

-

Instead of wasting your time here, try to make it happen in grunt. Or use something like https://github.com/sindresorhus/grunt-debug-files

**Comment by lzilioli** [comment]
@sindresorhus My understanding of grunt-debug-files is that it will show you what files match your glob patterns, but that is not what I'm interested in here. I'm trying to determine what files were written to the filesystem.

At this point, you've shown a puzzling lack of interest in having healthy discourse, which I do not at all understand, but I'm trying to figure out why, philosophically, you feel that your suggested course of action makes sense/is logical. I might be missing something but what is "boilerplate" about writing sensible output to the command line as a task runs? Can you point me to other commonly used or grunt-contrib tasks that have precisely zero output? I filed this issue because this is a solid grunt task, but from everything I know about grunt, it seems non-standard for grunt tasks to succeed silently, particularly when writing files to the filesystem.

You seem to think otherwise, so maybe share those thoughts?
