### ISSUE TITLE
Update to node-sass 3.x

### ISSUE THREAD

**Issue by DenisMir** [sindresorhus/grunt-sass#193]
It would be great if the `node-sass` dependency could be updated to the latest `3.x`. `node-sass` does include the latest `libsass` version. This version is a huge step since the `2.x` version.

**Comment by sindresorhus** [comment]
Yes, when a stable version of 3.0.0 is out I will upgrade.

**Comment by cibulka** [comment]
What about creating a "beta" branch of grunt-sass with `node-sass 3.x`? This approach works for https://github.com/krampstudio/grunt-jsdoc very well.

Users who want stable version of node-sass would continue to use `npm install --save-dev grunt-sass` and others who want the latest (me, @DenisMir and lots of others, I believe) would go with `npm install --save-dev grunt-sass@beta`. 

Personally, I can't wait for `@at-root` and another `3.x` goodies.
