### ISSUE TITLE
node-sass@3

### ISSUE THREAD

**Issue by jonathanong** [sindresorhus/grunt-sass#196]
node-sass@2 doesn't seem to work with iojs, and my teams wants to switch for compass (or whatever the slow, ruby version we're using is). any chance i can use node-sass@3 alpha locally by having grunt-sas sset the dependency to `>= 2 < 4` (haven't tried this before... npm might fail somewhere) and depending on `3.0.0-alpha.1` specifically in my app's package.json?

**Comment by abods** [comment]
Facing the same problem with Node 0.12 and i have to switch to 0.10 in order for grunt-sass to work!

**Comment by kevva** [comment]
Wouldn't it still try to use `node-sass@2`, even when a newer version of `node-sass` exists alongside?

**Comment by abods** [comment]
You are a star Kevva,
Just updated my node-sass to 2.0.1 and works perfect with node 0.12
Thank you.

**Comment by am11** [comment]
For v3-beta, I have made this commit: https://github.com/sindresorhus/grunt-sass/commit/c14beebc304816fc9b5973f0bd0a47a19556f52d. This is mostly for the breaking changes.

Till now, we have introduced couple of new options and features. The afore mentioned commit does not include them, but keep you going with latest Sass language compatibility.

Note using `"^3.0.0-"` will also work for getting latest of alpha, beta and rc.

HTH.

**Comment by sindresorhus** [comment]
It's now in master, so you can just run the following to get it:

```
npm cache clean && npm install --save-dev sindresorhus/grunt-sass
```

**Comment by trompx** [comment]
I tried the following grunt-sass versions 0.17.0 / 0.18.0 / 0.18.1 with the following packages : 
- node 0.12.2 / node-sass@2.1.1 or node-sass@beta
- node 0.10.35 or 0.10.36 / node-sass@2.0.0-beta

On my host machine (windows 8.1), all configs work, but on my VM (Ubuntu 14.04), I get the following error :
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?

Do you know what could I do, or any combinaison of node / node-sass / grunt-sass working ?

Thank you

**Comment by kevva** [comment]
Have you tried reinstalling like it suggests?

**Comment by trompx** [comment]
Ok this is quite tricky.

I use vagrant to sync my host files on my VM. The ideal would be to be able to just sync the core applications files from my host and install node_modules and composer packages only on the VM.

The thing is that the "vagrant rsync-auto" command does not take into account the excludes folder on initial rsync. Issues :
- https://github.com/mitchellh/vagrant/issues/3159
- https://github.com/mitchellh/vagrant/issues/4248

 So in my Vagrantfile even if I exclude node_modules, it will overrides node_modules folder in my VM.

So I tried the following :
- after the initial rsync on vagrant up, remove node_modules folder from vm
- "npm update" on the vm
- run grunt, change scss file on the host and manualy "vagrant rsync"

With the following, I managed to make work grunt-sass 0.18.1 with the following node versions :
- 0.10.35 / 0.10.36 / 0.10.38
It fails starting 0.11.0 (and I also tried 0.11.5, 0.12.0 and 0.12.2)

I have not tried it yet but I should vagrant up with only shared folder (no rsync), npm update on the VM to get the same files on my host. Then vagrant reload after changing the syncing method to rsync...

**Comment by xzyfer** [comment]
@trompx node-sass@3.0.0-beta address this issue. You should able to install it on both the host and VM with them overwriting each other.

**Comment by xzyfer** [comment]
node-sass v3.0.0 is live

**Comment by DenisMir** [comment]
Grr after switching to the final 3.0.0 release I'm once again getting `invalid operands for multiplication`.
