### ISSUE TITLE
--force option

### ISSUE THREAD

**Issue by geek876** [sindresorhus/grunt-sass#197]
How to pass --force option to sass ?

Warning:<path> :2354: error reading values after 16px
 Use --force to continue.

**Comment by kevva** [comment]
`grunt --force`

**Comment by kevva** [comment]
`Use --force to continue.` is outputted by grunt.

**Comment by geek876** [comment]
Kevva,

I have folder called styles with all my scss files in. There are also subfolder and more subfolders inside. I want grunt-saas to do all my files. How do i use recursive from top level i.e from styles/ and below ? There don't seem to be a flag/option for recursion
