### ISSUE TITLE
includePaths option is broken

### ISSUE THREAD

**Issue by bezoerb** [sindresorhus/grunt-sass#198]
When using version `grunt-sass` 0.18.1 i get the following error:
```shell
Running "sass:all" (sass) task
OptionParser::InvalidOption: invalid option: --include-paths=bower_components
```
I guess this is rather an issue with `node-sass` so i've already filed an issue there: https://github.com/sass/node-sass/issues/812
But i thought it would be good for you to know.

**Comment by bezoerb** [comment]
looks like this is no issue with `node-sass` and also no issue with `grunt-sass`

**Comment by kevva** [comment]
No issues at all ftw.

**Comment by bezoerb** [comment]
nope...
There was also `grunt-contrib-sass` installed so this one was used and there it should be an invalid option ;)
