### ISSUE TITLE
Can't run with new CSS selector

### ISSUE THREAD

**Issue by ozasadnyy** [sindresorhus/grunt-sass#199]
When I'm using new CSS selector `HTML /deep/ a` I get next error:
```
Running "sass:server" (sass) task
>> invalid top-level expression
>>   Line 42  Column 1  app\styles\partials\_global.scss
Warning:
```

Can you help me?

**Comment by sindresorhus** [comment]
https://github.com/sass/libsass/issues/452

Needs a libsass release, then a node-sass release, then we can get it here.
