### ISSUE TITLE
Use the libsass preformatted error

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/grunt-sass#201]
Instead of: https://github.com/sindresorhus/grunt-sass/blob/3f48c971cf1bcdcec67f47dbf439942639104db8/tasks/sass.js#L28

Need to wait for it to bubble up to `node-sass`.

Looks like it will be in libsass 3.2: https://github.com/sass/libsass/issues/938

@am11 Will this require any changes to `node-sass`? If yes, I'd be happy to open an issue.

**Comment by am11** [comment]
Oh I remember that one. :)

I will get back to you on that one, as I haven't started to implement libsass v3.2 beta3 and beta4. I hope it emits this info in JSON. Otherwise, I will send a PR to libsass hoping it will arrive in v3.2 stable is released.

**Comment by sindresorhus** [comment]
@xzyfer Did this ever happen?

**Comment by xzyfer** [comment]
@sindresorhus this does not appear to have happened yet. We can do it node-sass but I'd prefer to push it into LibSass. This isn't my area of LibSass but I'll open a new issue.

**Comment by xzyfer** [comment]
Current error output from node-sass 3.4.0-beta

```
> require('./lib/index').render({ data: "foo()" }, function(err, res) { console.log(err); });
undefined
> { [Error: Invalid CSS after "foo()": expected "{", was ""]
  message: 'Invalid CSS after "foo()": expected "{", was ""',
  column: 5,
  line: 1,
  file: 'stdin',
  status: 1 }
```

**Comment by xzyfer** [comment]
LibSass PR https://github.com/sass/libsass/pull/1582. If/when this lands node-sass will get it for free.

**Comment by cmacdonnacha** [comment]
+1 I'm also getting this error

**Comment by xzyfer** [comment]
This will land in the next version.
