### ISSUE TITLE
Option sourceMapRoot has no effect.

### ISSUE THREAD

**Issue by rickhub** [sindresorhus/grunt-sass#204]
I'm trying to customize the source map root path, but it has no effect at all. My config looks like:

```js

grunt.initConfig({
	sass:{
		options:{
			sourceMap: true,
			sourceMapRoot: '../source',
			outputStyle: 'compressed'
		},
		dev:{
			files:{
				'build/app.min.css':[
					'source/**/*.scss'
				]
			}
		}
	}
});
``` 

The created .map-file looks like:

```js
{
	"version": 3,
	"file": "app.min.css",
	"sources": [
		"../app.scss",
		"../features/welcome/_welcome.scss"
	],
	"sourcesContent": [],
	"mappings": "ACAA,KACC,QAAS,KDCV,GACC,YAAa,oCACb,UAAW,IACX,eAAgB",
	"names": []
}
```

Why is my setting ignored?

**Comment by am11** [comment]
`sourceMapRoot` was added in node-sass [in yesterday's beta build](https://github.com/sass/node-sass/releases/tag/v3.0.0-beta.5). Please update the node-sass dependency and retry. The value of `sourceMapRoot` should be emitted as `sourceRoot` in `.map` file.

**Comment by troyblank** [comment]
I have the same issue; but as @am11 stated it seems the issues has been resolved in a beta node-sass (https://github.com/sass/node-sass/issues/731); excited when grunt-sass will start using that version of node-sass as a dependency once it's out.
