### ISSUE TITLE
Sourcemaps: source path generation

### ISSUE THREAD

**Issue by rubjo** [sindresorhus/grunt-sass#206]
Thank you for providing a speedy Sass plugin for Grunt.

I need some help setting up grunt-sass with source map support correctly for this directory structure:
```
scss/
    partials/
        extras/
            _file.scss
            _file.scss
            _file.scss
        modules/
            _file.scss
            _file.scss
            _file.scss
        framework/
            _file.scss
            _file.scss
            _file.scss
        _modules.scss
        _framework.scss
    utilities/
        _variables.scss
        _functions.scss
        _mixins.scss
    main.scss
css/
    main.css
    main.css.map
```

The main.scss only @imports other Sass files.

sass task configuration:
```
sass: {
    options: {
        sourceMap: true
    },
    files: {
        'css/main.css': 'scss/main.scss'
    }
},
```

Compiling from scss to css works nicely, but main.css.map ends up looking for the source sass files in the wrong directory, e.g. "../partials/framework/_file.scss". How can I fix this?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by rubjo** [comment]
Thanks for pointing me in the right direction.

Seems my issue is the same as http://stackoverflow.com/questions/29083963/grunt-sass-sourcemaps-sass-wrong-path.

**Comment by tivnet** [comment]
@rubjo Having the same problem, and no solution on StackOverflow, I "patched" `grunt-sass/tasks/sass.js`:

	if (opts.sourceMap && !opts.sourceMapEmbed) {
		res.map = res.map.replace('../../','');

Of course, this is an ugly workaround. Hope @sindresorhus can fix this properly (thank you in advance!).

**Comment by xzyfer** [comment]
This should be resolved with grunt-sass@^1
