### ISSUE TITLE
Desaturate not desaturating

### ISSUE THREAD

**Issue by Thomeuxe** [sindresorhus/grunt-sass#210]
Hi there,

I get some weird output color when using desaturate.

For exemple this  : desaturate(#62B1C9, 100%) (blue) give me this color :  #CC7960 (red)

Any idea ?

Thank you !
Thomeuxe

**Comment by xzyfer** [comment]
Thanks for the report @Thomeuxe. This has been fixed in Libsass 3.2.0, and will be in the next version of grunt-sass.
