### ISSUE TITLE
Node Sass & Libsass Update

### ISSUE THREAD

**Issue by shaunbent** [sindresorhus/grunt-sass#212]
There have been more updates to libsass and nodesass - any chance of another release to pull these through?

- node-sass - 3.1.0 - https://github.com/sass/node-sass/releases/tag/v3.1.0
- libsass - 3.2.4 - https://github.com/sass/libsass/releases/tag/3.2.4

I'll open a PR tomorrow to update if thats ok?

**Comment by sindresorhus** [comment]
https://nodesource.com/blog/semver-tilde-and-caret

**Comment by shaunbent** [comment]
Sorry I didn't even spot that. Cheers for the article.
