### ISSUE TITLE
incompatible node-sass version

### ISSUE THREAD

**Issue by flecno** [sindresorhus/grunt-sass#217]
I can't build my project since node-sass 3.2.0 is released. My grunt tasks throws this error:

```
Running "sass:default" (sass) task
Fatal error: Arguments to path.resolve must be strings
```
Any idea whats wrong? My quickfix is using node-sass 3.1.2 (https://github.com/flecno/grunt-sass/commit/35b6e0e00619a41c2c6127e66072ad73183c41fa)

**Comment by sindresorhus** [comment]
Run `grunt sass --stack` and post it here as there's no way to help you without more info.

**Comment by sindresorhus** [comment]
But this is an `node-sass` issue and should be opened there instead: https://github.com/sass/node-sass/issues/new

**Comment by arthurvr** [comment]
ping @flecno
