### ISSUE TITLE
node-sass 3.x performance regressions

### ISSUE THREAD

**Issue by localpcguy** [sindresorhus/grunt-sass#221]
As noted in the bug upstream, node-sass 3.x has a pretty large performance regression. I had to back down to the previous version of grunt-sass to avoid the hit (my app went from 500-700ms Sass compile time to about 4.5s).

https://github.com/sass/node-sass/issues/970

This is in the upstream, just referencing here for others that may notice the same thing.

**Comment by kevva** [comment]
Thanks for the heads up but I don't think we need a duplicate issue on this repo :).
