### ISSUE TITLE
SourceMap referes to wrong files and lines

### ISSUE THREAD

**Issue by dawidk92** [sindresorhus/grunt-sass#222]
![zrzut ekranu 2015-06-25 o 12 55 43](https://cloud.githubusercontent.com/assets/7023167/8352952/ac38c704-1b39-11e5-8631-0b2883c79cb1.png)

![zrzut ekranu 2015-06-25 o 12 57 15](https://cloud.githubusercontent.com/assets/7023167/8352957/bd4891aa-1b39-11e5-8333-394d8b55b775.png)

Mac OS X 10.10.3
grunt: 0.4.5
grunt-sass: 1.0.0

**Comment by sindresorhus** [comment]
Should be posted in the node-sass issue tracker.
