### ISSUE TITLE
scss comments blocking render to css

### ISSUE THREAD

**Issue by whitehorse5353** [sindresorhus/grunt-sass#223]
Hi,

when i try to render a block of SCSS like this 

.drlp{ 
  background-color: red;
  color: red;
  ul{
//    width: 300px;
    li{
      color: gray;
    }
  }
 }

it throws a drlp.scss:1: invalid property name Use --force to continue. is there a option to stripeBanners and comments ?

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the libsass [issue tracker](https://github.com/hcatlin/libsass/issues).*

-

> is there a option to stripeBanners and comments ?

If it's not in the docs there clearly isn't.
