### ISSUE TITLE
More detail options example

### ISSUE THREAD

**Issue by 58bits** [sindresorhus/grunt-sass#227]
I realize the readme is pointing to libsass for options, but I think a more detailed example would help - for example...

```
    /**
     * Sass
     */
    sass: {
      dev: {
        options: {
          outputStyle: 'expanded',
          sourceMap: true
        },
        files: [{
          expand: true,
          cwd: 'assets/scss',
          src: ['*.scss'],
          dest: 'public/css/',
          ext: '.css'
        }]
      },
      dist: {
        options: {
          outputStyle: 'expanded',
          sourceMap: false
        },
        files: [{
          expand: true,
          cwd: 'assets/scss',
          src: ['*.scss'],
          dest: 'public/css/',
          ext: '.css'
        }]
      }
    },
```

**Comment by sindresorhus** [comment]
Read the grunt docs if you want something more comprehensive. The task config for files and options is the same for all grunt tasks as they just use the grunt APIs.

**Comment by 58bits** [comment]
Agreed, although there's no harm in providing a more comprehensive example, as other grunt task runners do. How could providing more help and documentation be a bad thing?
