### ISSUE TITLE
Upgrade to node-sass 3.2.0

### ISSUE THREAD

**Issue by DennisBecker** [sindresorhus/grunt-sass#229]
It would be nice if you could release a new version with support for latest node-sass version. I had a problem with node-sass 3.0.0 and libsass 3.2.0 so I have to stay on version 0.18.1 so far.

**Comment by xzyfer** [comment]
The latest 3.x version will be used automatically.

**Comment by DennisBecker** [comment]
Thanks, didn't see that at first, maybe it is too early in the morning :)
