### ISSUE TITLE
libsass binding not found

### ISSUE THREAD

**Issue by jesus-crysist** [sindresorhus/grunt-sass#234]
I'm trying to run grunt-sass in my project but I get following message:
```
> Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found in /**/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
```
When I go to *node_modules/grunt-sass/node_modules/node-sass/vendor/* I can find only *linux-x64-11* folder with *binding.node* inside.

**Comment by kevva** [comment]
> Issues with the output should be reported on the libsass issue tracker.
