### ISSUE TITLE
Error not thrown on failure to extend

### ISSUE THREAD

**Issue by sandwichsudo** [sindresorhus/grunt-sass#236]
I'm not sure whether this is a problem with grunt-sass, node-sass or even libsass, but I'm finding with an otherwise empty .scss file, compiling eg

    .foo{
        @extend .bar;
    }

does not throw an error saying something "The selector ".bar" was not found.", when it should.

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the libsass [issue tracker](https://github.com/hcatlin/libsass/issues).*
