### ISSUE TITLE
can't use & (ampersand) inside mixin, get error: Fatal error: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by Ghostavio** [sindresorhus/grunt-sass#237]
Not sure if this is a problem here or on node-sass or on libsass, but basically having something like this in your code will throw that error:
```css
@mixin whatever() {
    & {
        @content; // or anything else
    }
}
```

Throws the following (weird) error: Fatal error: Arguments to path.resolve must be strings.

**Comment by Ghostavio** [comment]
funny thing is, if I try something like this:

```css
@mixin whatever() {
    font-family: &;
}
```

I get the selector name on the outputted file.

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the libsass [issue tracker](https://github.com/hcatlin/libsass/issues).*

**Comment by Ghostavio** [comment]
it's not an issue with the output, it's an error.
