### ISSUE TITLE
1.1.0-beta is not compatible with 1.0.0

### ISSUE THREAD

**Issue by koenpunt** [sindresorhus/grunt-sass#245]
I had `grunt-sass` in my `package.json` like so:
```json
{
"grunt-sass": "^1.0.0"
}
```
And that makes npm use the 1.1.0-beta version.

Does this mean `grunt-sass` does not follow semver? 
Or is this just a beta glitch?

**Comment by sindresorhus** [comment]
Broken npm version. Upgrade npm.

**Comment by koenpunt** [comment]
Oh well. Thanks for the quick response! But still, does `grunt-sass` follow semver?

**Comment by arthurvr** [comment]
Yes it does.

**Comment by koenpunt** [comment]
:+1:
