### ISSUE TITLE
Possible to use grunt-sass to lint via watch?

### ISSUE THREAD

**Issue by cgtm** [sindresorhus/grunt-sass#246]
Hi,

Was wondering if it would be possible to lint my sass code on the fly with grunt-sass? Right now, I'm trying to remove ruby altogether from a project and it uses grunt-scss-lint for linting (which uses sass via ruby).

Thanks for any info/pointers.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by cgtm** [comment]
OK, thanks.

Here's the link to the question on StackOverflow:
http://stackoverflow.com/questions/32758021/how-to-use-grunt-sass-to-lint-on-the-fly

**Comment by xzyfer** [comment]
https://www.npmjs.com/package/grunt-sass-lint
