### ISSUE TITLE
Grunt wont exit if there is a SASS error.

### ISSUE THREAD

**Issue by jshemas** [sindresorhus/grunt-sass#247]
Hello,

Lets say I have a grunt sass config that looks something like...

```javascript
'sass': {
	'options': {
		'functions': {
			'functionName()': function() {
				var sass = require('node-sass'),
					output = 'test';
				output = new sass.types.String(output);
				return output;
			}
		}
	},
	'build': {
		'options': {
			'sourceMap' : true,
			'outputStyle': 'nested'
		},
		'files': {
			'base/css/main.css': 'base/sass/main.scss'
		}
	}
}
```

And inside main.scss I have some invalid sass. Like `position: ;` 

If I run the sass build task, it will output `>> style declaration must contain a value` error but it wont exit grunt. And then I have to force quit that terminal tab. If I comment out the 'functions' part of my options grunt will exit after that error just fine.

Thanks ahead of time!

**Comment by sindresorhus** [comment]
That thing is still `experiemental` https://github.com/sass/node-sass#functions--v300---experimental

This task just passes your option to `node-sass`, so it's highly likely something wrong there.

Try reproducing the issue with the vanilla `node-sass` API and open an issue there instead.
