### ISSUE TITLE
Libsass version 

### ISSUE THREAD

**Issue by pimschaaf** [sindresorhus/grunt-sass#249]
Great work. Though I have a hard time finding out which libsass version is actually being used in this wrapper.

I'd suggest adding the libsass version to the readme.md. Combined with http://sass-compatibility.github.io/ it would give better insight in the feature parity of this wrapper vs the grunt-contrib-sass wrapper.

Thanks!

**Comment by sindresorhus** [comment]
Can't really document it as the node-sass dependency is loose, so it will be out of date quickly. The best way to find out is to run `grunt sass --verbose` and it will show you. You could also look at the changelog for the newest node-sass version.

**Comment by pimschaaf** [comment]
Thanks for your quick response.
Works for me. Should this be added to the readme?

Keep up the good work!

**Comment by xzyfer** [comment]
@pimschaaf feel free to open a PR :)
