### ISSUE TITLE
Why does `grunt-sass` pull in all minor changes of `node-sass`?

### ISSUE THREAD

**Issue by danoc** [sindresorhus/grunt-sass#255]
Hello! 

The `3.3.0` Libsass release introduced a regression (https://github.com/sass/libsass/issues/1654) that was picked up by `node-sass` `v3.4.0`. This was in turn picked up by `grunt-sass` `v1.0.0`, the version we use, because the `package.json` is configured to pull all minor and patch releases of `node-sass`.

We had to fork `grunt-sass` and force it to use an older version of `node-sass` to patch our issue until the Libsass developers respond (https://github.com/sindresorhus/grunt-sass/compare/master...optimizely:daniel/node-sass-3-3-3).

I'd like to know if there is a particular reason that `grunt-sass` pulls in all minor (`3.X.X`) releases of `node-sass`. I'd recommend only pulling in patches or lock `grunt-sass` to a specific version of `node-sass` and release at the same cadence.

I'd be happy to elaborate if that made no sense!

**Comment by sindresorhus** [comment]
That's how npm and semver works. Even with your suggestion it could still break in a patch release. You should be using shrinkwrap on your part.

https://nodesource.com/blog/semver-tilde-and-caret
http://semver.org
