### ISSUE TITLE
Npm install fails on grunt-sass

### ISSUE THREAD

**Issue by cmacdonnacha** [sindresorhus/grunt-sass#256]
Hi,

I have `grunt-sass 1.0.0` in my package.json file and `npm install` always fails when it gets to `grunt-sass`. If I take `grunt-sass` out of the package.json file it works fine and installs all node packages.

**Console Output**
spawn-sync@1.0.13 postinstall C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
node postinstall

node-sass@3.4.1 install C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass
node scripts/install.js

Binary downloaded and installed at C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node

node-sass@3.4.1 postinstall C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass
node scripts/build.js

` C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc' -> 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc' -> 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\cmacdonnacha.GLOBAL\\AppData\\Roaming\\npm-cache\\lru-cache\\2.7.0\\package\\package.json.cc0a32d9edbcac892eecc5eec7efc9fc',
npm ERR!   dest: 'C:\\Users\\cmacdonnacha.GLOBAL\\AppData\\Roaming\\npm-cache\\lru-cache\\2.7.0\\package\\package.json',
npm ERR!   parent: 'minimatch' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ngProj(18-10-2015)\npm-debug.log

**Npm debug log output**
124555 info install eslint@1.7.3
124556 info postinstall eslint@1.7.3
124557 verbose unlock done using C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\_locks\eslint-a24554a563b5ec0d.lock for C:\dev\ngProj(18-10-2015)\node_modules\eslint
124558 info postinstall node-sass@3.4.1
124559 verbose unsafe-perm in lifecycle true
124560 verbose unlock done using C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\_locks\node-sass-1fe3f2892b3dda77.lock for C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass\node_modules\node-sass
124561 verbose about to build C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass
124562 info build C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass
124563 info linkStuff grunt-sass@1.1.0
124564 silly linkStuff grunt-sass@1.1.0 has C:\dev\ngProj(18-10-2015)\node_modules as its parent node_modules
124565 verbose linkBins grunt-sass@1.1.0
124566 verbose linkMans grunt-sass@1.1.0
124567 verbose rebuildBundles grunt-sass@1.1.0
124568 verbose rebuildBundles [ '.bin', 'each-async', 'node-sass', 'object-assign' ]
124569 info install grunt-sass@1.1.0
124570 info postinstall grunt-sass@1.1.0
124571 verbose unlock done using C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\_locks\grunt-sass-9f89e32ade1d08d6.lock for C:\dev\ngProj(18-10-2015)\node_modules\grunt-sass
124572 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc' -> 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json'
124572 verbose stack     at Error (native)
124573 verbose cwd C:\dev\ngProj(18-10-2015)
124574 error Windows_NT 6.1.7601
124575 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
124576 error node v4.2.1
124577 error npm  v2.14.7
124578 error path C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc
124579 error code EPERM
124580 error errno -4048
124581 error syscall rename
124582 error Error: EPERM: operation not permitted, rename 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc' -> 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json'
124582 error     at Error (native)
124582 error  { [Error: EPERM: operation not permitted, rename 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json.cc0a32d9edbcac892eecc5eec7efc9fc' -> 'C:\Users\cmacdonnacha.GLOBAL\AppData\Roaming\npm-cache\lru-cache\2.7.0\package\package.json']
124582 error   errno: -4048,
124582 error   code: 'EPERM',
124582 error   syscall: 'rename',
124582 error   path: 'C:\\Users\\cmacdonnacha.GLOBAL\\AppData\\Roaming\\npm-cache\\lru-cache\\2.7.0\\package\\package.json.cc0a32d9edbcac892eecc5eec7efc9fc',
124582 error   dest: 'C:\\Users\\cmacdonnacha.GLOBAL\\AppData\\Roaming\\npm-cache\\lru-cache\\2.7.0\\package\\package.json',
124582 error   parent: 'minimatch' }
124583 error Please try running this command again as root/Administrator.
124584 verbose exit [ -4048, true ]
124585 verbose unbuild node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\npmconf
124586 info preuninstall npmconf@2.1.1
124587 info uninstall npmconf@2.1.1
124588 verbose unbuild rmStuff npmconf@2.1.1 from C:\dev\ngProj(18-10-2015)\node_modules
124589 verbose unbuild rmStuff in C:\dev\ngProj(18-10-2015)\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules
124590 info postuninstall npmconf@2.1.1
124591 silly gentlyRm C:\dev\ngProj(18-10-2015)\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\npmconf is being purged from base C:\dev\ngProj(18-10-2015)
124592 verbose gentlyRm don't care about contents; nuking C:\dev\ngProj(18-10-2015)\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\npmconf
124593 silly vacuum-fs purging C:\dev\ngProj(18-10-2015)\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\npmconf
124594 silly vacuum-fs quitting because other entries in C:\dev\ngProj(18-10-2015)\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules
124595 verbose unbuild node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules\minimatch
124596 info preuninstall minimatch@0.2.14
124597 info uninstall minimatch@0.2.14
124598 verbose unbuild rmStuff minimatch@0.2.14 from C:\dev\ngProj(18-10-2015)\node_modules
124599 verbose unbuild rmStuff in C:\dev\ngProj(18-10-2015)\node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules
124600 info postuninstall minimatch@0.2.14
124601 silly gentlyRm C:\dev\ngProj(18-10-2015)\node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules\minimatch is being purged from base C:\dev\ngProj(18-10-2015)
124602 verbose gentlyRm don't care about contents; nuking C:\dev\ngProj(18-10-2015)\node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules\minimatch
124603 silly vacuum-fs purging C:\dev\ngProj(18-10-2015)\node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules\minimatch
124604 silly vacuum-fs quitting because other entries in C:\dev\ngProj(18-10-2015)\node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule\node_modules
124605 verbose unbuild node_modules\grunt-contrib-watch\node_modules\gaze\node_modules\globule
124606 info preuninstall globule@0.1.0

**Comment by sindresorhus** [comment]
I don't see anything relevant to grunt-sass in the logs. Looks like the normal npm breakage or permission problem. Try upgrading to npm@3 and/or run as sudo.

**Comment by cmacdonnacha** [comment]
But it only ever happens when "grunt-sass" is included. All other packages are fine so it has to be grunt-sass.

  "devDependencies": {
    "eslint": "^1.7.3",
    "eslint-plugin-angular": "^0.13.0",
    "grunt": "^0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-continue": "^0.1.0",
    "grunt-ng-annotate": "^1.0.1",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compass": "^1.0.2",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-htmlmin": "^0.5.0",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-eslint": "^17.3.1",
    "grunt-express": "^1.4.1",
    "grunt-html2js": "^0.3.0",
    "grunt-karma": "^0.12.1",
    "grunt-newer": "^1.1.0",
    "grunt-run": "^0.5.2",
    "grunt-sass": "^1.1.0",
    "karma": "^0.13.14",
    "karma-coverage": "^0.2.7",
    "karma-jasmine": "^0.3.1",
    "karma-junit-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^0.1.4",
    "time-grunt": "^1.0.0"
  },

**Comment by cmacdonnacha** [comment]
If I take "grunt-sass" out from the devDependencies everything installs fine.

**Comment by sindresorhus** [comment]
That doesn't necessarily mean it's a problem with `grunt-sass`. From experience it's always a lot more likely a problem with npm. Try what I recommended.

**Comment by cmacdonnacha** [comment]
Thanks. The latest Nodejs **4.2.1** seems to come with npm version **2.14.7**. That's the version I have but I'll try updated npm separately to version 3.

**Comment by cmacdonnacha** [comment]
@sindresorhus that worked. I ran `npm install npm` and it installed version **3.3.9**. It looks like with the new npm everything gets installed to the `node_modules` folder now, even peer dependencies.
