### ISSUE TITLE
Update to node-sass 3.4.1

### ISSUE THREAD

**Issue by y-a-v-a** [sindresorhus/grunt-sass#257]
Hi,
I don't want to be pushy but it would be great if you could update grunt-sass to use node-sass 3.4.1?
Thanks!
Vincent

**Comment by sindresorhus** [comment]
I don't want to be pushy either, but I get a ton of these useless issues where people don't understand semver and I have to explain it to them taking away time from actual development ;)

Just reinstall this task and you have it.

https://nodesource.com/blog/semver-tilde-and-caret

**Comment by y-a-v-a** [comment]
Sir, yes sir!
