### ISSUE TITLE
load-grunt-tasks

### ISSUE THREAD

**Issue by borisdamevin** [sindresorhus/grunt-sass#285]
Hi,

Why we can no longer use the plugin "load-grunt-tasks" with grunt-sass 3.0.0?

We are obliged to reimplement the sass config in the Gruntfile.js file obligatorily?

Thank you.

**Comment by noahcooper** [comment]
+1.

**Comment by Suriv** [comment]
Can you show your gruntfile settings?

**Comment by borisdamevin** [comment]
I don't have sass setting on Gruntfile.js, is a file outside, for use _"load-grunt-tasks"_.

Why we need to put the sass setting on Gruntfile.js since grunt-sass version 3.0.0?
