### ISSUE TITLE
"Original" argument must be of type Function.  Received type undefined

### ISSUE THREAD

**Issue by jasonsturges** [sindresorhus/grunt-sass#288]
In upgrading a project from v2.1.0 to v3.0.1, I'm now receiving an error:

> Fatal error: The "original" argument must be of type Function. Received type undefined

Not sure what this is referencing; however, is new after the upgrade.

SASS portion of Gruntfile.js:

```js
sass: {
    dist: {
        options: {
            implementation: 'sass-dist',
            outputStyle: 'compact',
            sourceComments: false,
            sourceMap: true
        },
        files: {
            'css/example.css': 'sass/example.scss',
        }
    }
}
```

**Comment by tobsn-me** [comment]
I ran into this error, too. To fix this, follow these steps:

1. Add **node-sass** to your project
    ```zsh
    $ npm i node-sass --save-dev
    ```

1. Include **node-sass** in your Gruntfile
    ```javascript
    const sass = require('node-sass');
    ```
2. In your sass options, change the following line

    from
    ```javascript
    implementation: 'sass-dist'
    ```
    to
    ```javascript
    implementation: sass
    ```

**Comment by JonMcL** [comment]
If anyone ends up here and can't figure it out, this might help ---

I accidentally (stupidly?) had the 'implementation' argument as a string, so change
```js
implementation: 'sass'
```
to
```
implemenation: sass
```

This of course depends on the 
```js
const sass = require('node-sass');
```
line to populate the sass object.
