### ISSUE TITLE
path problem?

### ISSUE THREAD

**Issue by volkanongun** [sindresorhus/grunt-sass#298]
my application silently fails and doesn't generate any css/scss files. I'm suspicious of files : [no files] log from verbose output. 

`grunt.config('sass', {
  sass: {
    options: {
      implementation: sass,
      sourceMap: true
    },
    dist: {
      files: {
        'tmp/app.css': 'src/sass/styles.scss'
      }
    }
  }
});`

**my verbose grunt output :**

Verifying property sass.sass exists in config...OK
File: [no files]
Options: precision=10, implementation={"info":"node-sass\t4.13.1\t(Wrapper)\t[JavaScript]\nlibsass  \t3.5.4\t(Sass Compiler)\t[C/C++]","types":{},"TRUE":{},"FALSE":{},"NULL":{}}, sourceMap

node-sass	4.13.1	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

**Comment by PascalAOMS** [comment]
Got the same issue.

**Comment by volkanongun** [comment]
Lol i migrated to Parceljs, completely abandoned grunt.

**Comment by PascalAOMS** [comment]
Unfortunately I'm in the SAP Commerce environment. Can't quickly implement a JS bundler.

**Comment by csloisel** [comment]
After banging my head against a wall for a really long time with this i finally got it to work by removing the `dist` object.

So instead of: `options: { dist: { files: {} } }` I used `options: { files: {} }`

**Comment by marcovtwout** [comment]
@csloisel Perhaps you had the keys and options switched. Here's a working example with both generic options and dev/dist based.

```js
sass: {
    options: {
        implementation: require('node-sass'),
    },
    dev: {
        options: {
            sourceMap: true
        },
        files: {
            'public/css/main.css': 'scss/main.scss'
        }
    },
    dist: {
        options: {
            outputStyle: 'compressed'
        },
        files: {
            'public/css/main.min.css': 'scss/main.scss'
        }
    },
},
```

Guess this issue can be closed.
