### ISSUE TITLE
Node-Sass version 4.7.2 unavailable as git binary

### ISSUE THREAD

**Issue by 1996dylanriley** [sindresorhus/grunt-sass#303]
Node-Sass needs upgrading as when running npm install I get the following error:

Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node"

If you try visiting that URL you will see that it returns a 404 so I suggest upgrading to v4.14.1 which is available as a binary here: 
https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-64_binding.node

**Comment by sindresorhus** [comment]
`node-sass` is not a dependency here. This is a problem for you to solve yourself.
