### ISSUE TITLE
Use new node-sass Major Version 5.0

### ISSUE THREAD

**Issue by polarius11** [sindresorhus/grunt-sass#305]
the node-sass dependency 4.X using node-gyp version 3.8 and this version does not fit very well in our build system because our environment is to new for this old node-gyp version and throws exceptions.

It would be nice to use the node-sass 5.X dependency because it use a newer node-gyp version.

**Comment by sindresorhus** [comment]
`grunt-sass` doesn't depend on `node-sass`, so it's completely up to you to upgrade such a dependency.
