### ISSUE TITLE
Load module from grunt.loadNpmTasks

### ISSUE THREAD

**Issue by semiromid** [sindresorhus/grunt-sass#306]
Hello, @Richienb  !

Thanks a lot for your work!

I would like to make a note:

Can be loaded without `require('load-grunt-tasks')(grunt);` use `grunt.loadNpmTasks('grunt-sass');`

```
const sass = require('node-sass');

grunt.initConfig({
	sass: {
		options: {
			implementation: sass,
			sourceMap: true
		},
		dist: {
			files: {
				'main.css': 'main.scss'
			}
		}
	}
});

grunt.loadNpmTasks('grunt-sass');

grunt.registerTask('default', ['sass']);
```

**Comment by Richienb** [comment]
I'm just a contributor, thank @sindresorhus instead.

**Comment by sindresorhus** [comment]
I'm aware it can be, it's just that `load-grunt-tasks` make it much easier when you have more than one task.
