### ISSUE TITLE
Warning: source string:1: error: invalid top-level expression

### ISSUE THREAD

**Issue by areel** [sindresorhus/grunt-sass#48]
Issue #41  Warning: source string:1: error: invalid top-level expression
Issue #46: Warning: source string:1: error: invalid top-level expression

Ran into this error yesterday on latest grunt-sass, on Windows8.

Read the two links above and  giving the full path does not resolve it.
If I put the files in the same directory that I am running the grunt command from, it will succeed.
I believe it may be related to mishandling the path separator symbol

**Comment by xtianus79** [comment]
so is this an issue with grunt? and if so are they fixing it... seems like a long time ago this was reported.
