### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by sketchynix** [sindresorhus/grunt-sass#95]
I just updated grunt-sass to the latest buil and am getting an error with the files I attempt to import from another folder. 

My rough website structure is like this 

/website/scss
/module/navigation/scss
/module/blog/scss

My gruntfile, node modules, and config are inside of /website/ 

My config looks like this:

```
sass: {
            dist: {
                options: {
                    includePaths: ['scss/', 'bower_components/foundation/scss/'],
                    outputStyle: 'compressed'
                },
                files: {
                    'dev-css/website.css': 'scss/website.scss',
                }
            }
        }
```

Each scss file imports inside of a module (eg. /module/blog/scss/blog.scss) imports  a main utility file (from the /website/scss folder)Before the latest update this worked correctly as the utility files path is in the includePaths option. Now I get the error:
error: file to import not found or unreadable: "utility"

This error goes away when I replace the tasks/sass.js with the previous version. I am on a Windows 8.1 box

**Comment by jamesharrington** [comment]
Double check and make sure that file exists. I had this problem and it turned out to be bower.json didnt have the package saved and once i got it on my server i bower install and it didnt install said package meaning sass couldnt find what i told it to look for
